def COLOR_MAP = [
    'SUCCESS': 'good', 
    'FAILURE': 'danger',
]
pipeline {
    agent any
    tools {
        maven "MAVEN3"
        jdk "OracleJDK8"
    }

    environment {
        cluster = "vproprod"
        //the service name which we will use to create the container to deploy the image
        service ="vproappprodsvc"
    }


    stages {
        
        stage('Deploy to prod ECS staging'){
            steps {
                withAWS(credentials:'awscreds',region:'us-east-1'){
                    //we are telling the service to forcefully delete the old container and deploy the new container with the latest image 
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment'
                }
            }
        }
    }
    post {
        //always block means it will always get executed.
        always {
            echo 'Slack Notifications.'
            // "slackSend" is the plugin that we Installed and we are passing 3 arguments to it
            // 3 arguments : one is the channel , one is the color and one is the message 
            slackSend channel: '#jenkinscicd',
                color: COLOR_MAP[currentBuild.currentResult],
                message: "*${currentBuild.currentResult}:* Job ${env.JOB_NAME} build ${env.BUILD_NUMBER} \n More info at: ${env.BUILD_URL}"
        }
    }
}
